### ISSUE TITLE
Add `Promise.both`

### ISSUE THREAD

**Issue by anmonteiro** [aantron/promise#55]
This is useful for the `and*` binding operator.

Currently I'm using:

```reason
  let both = (x, y) => {
    Promise.all([x, y])
    ->Promise.map(
        fun
        | [x, y] => (x, y)
        | _ => assert(false),
      );
  };
```

**Comment by aantron** [comment]
@anmonteiro [`Promise.all2`](https://github.com/aantron/promise/blob/51001f911ff31ecf51a633fba9f782769a2726c9/src/js/promise.rei#L135-L137) should be suitable for this. It was added for #36 and I called it `all2` because I didn't think there was a neat set of special names that also covered `all3`, `all4`, etc. :) It's mentioned at the end of [Concurrent combinations](https://github.com/aantron/promise#concurrent-combinations).

**Comment by anmonteiro** [comment]
Heh, indeed. Missed it, thanks!
